-- AlterTable
ALTER TABLE "Episode" ALTER COLUMN "rating" SET DEFAULT 10,
ALTER COLUMN "rating" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "rating" SET DEFAULT 10,
ALTER COLUMN "rating" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Season" ALTER COLUMN "rating" SET DEFAULT 10,
ALTER COLUMN "rating" SET DATA TYPE DECIMAL(65,30);
